name: iOS Simulator
on:
  workflow_dispatch:

jobs:
  iOS-tests:
    timeout-minutes: 100
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 12.2
        run: sudo xcode-select -s /Applications/Xcode_12.2.app && xcodebuild -version

      - name: install simulator
        run: xcversion simulators --install='iOS 14.2'

      - name: Prepare iOS 14.2 simulator
        run: |
         sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
         sudo ln -s /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.4.simruntime
         xcrun simctl list runtimes
         xcrun simctl create iPhone_11 "iPhone 11" "com.apple.CoreSimulator.SimRuntime.iOS-14-2"
         xcrun simctl list devices 14.2
         
      - name: Set up Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: |
         npm run local
        continue-on-error: true
