name: iOS Simulator

on: [ push ]

jobs:
  iOS-tests:
    timeout-minutes: 100
    runs-on: macos-11
    using: 'node14'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer && xcodebuild -version

      - name: Prepare iOS 14.5 simulator
        run: |
         sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
         sudo ln -s /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.5.simruntime
         xcrun simctl list runtimes
         xcrun simctl create iPhone_11 "iPhone 11" "com.apple.CoreSimulator.SimRuntime.iOS-14-5" > deviceid.txt
           DEVICEUUID=`cat deviceid.txt`
           echo $DEVICEUUID
           xcrun simctl boot $DEVICEUUID &
         xcrun simctl list devices 14.5
         open -a Simulator.app
         sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer
         xcrun --sdk iphonesimulator --show-sdk-version

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: |
         npm run local
        continue-on-error: true
