name: iOS Simulator

on: [ push ]

jobs:
  iOS-tests:
    timeout-minutes: 100
    runs-on: macos-11
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer && xcodebuild -version

      - name: Prepare iOS 14.4 simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.4.simruntime
          xcrun simctl list runtimes
          PHONE_ID= "$(xcrun simctl list devices 14.4| grep "iPhone 8 Plus" |  awk '{print substr($0,length($0)-36,24)}')"
          open -a Simulator --args -CurrentDeviceUDID $PHONE_ID
          echo $PHONE_ID
          xcrun simctl list devices 14.4

      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '14.15.0'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: |
         npm run local
        continue-on-error: true
