name: iOS Simulator
on:
  workflow_dispatch:

jobs:
  iOS-tests:
    timeout-minutes: 100
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer && xcodebuild -version

      - name: install simulator
        run: xcversion simulators --install='iPhone 14'

      - name: Prepare iOS 14.2 simulator
        run: |
         sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
         sudo ln -s /Applications/Xcode_14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.2.simruntime
         xcrun simctl list runtimes
         xcrun simctl create iPhone_11 "iPhone 11" "com.apple.CoreSimulator.SimRuntime.iOS-14-2" > deviceid.txt 
           DEVICEUUID=`cat deviceid.txt`          
           echo $DEVICEUUID                     
           xcrun simctl boot $DEVICEUUID &
         xcrun simctl list devices 14.2


      - name: Set up Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      - name: Install dependencies
        run: npm i

      - name: Start the Appium Server
        run: ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > appium.log &
      # Poll for Appium Server to Start
      - name: Poll for Appium Server to Start
        run: |
          until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
            sleep 5
          done
      - name: Run tests
        run: |
         npm run local
        continue-on-error: true
