name: iOS Simulator

on: [ push ]

jobs:
  iOS-tests:
    timeout-minutes: 100
    runs-on: macos-11
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer && xcodebuild -version

      - name: Prepare iOS 14.5 simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 11'
    
      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '14.15.0'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: |
         npm run local
        continue-on-error: true
