name: Android emulator
on:
  workflow_dispatch:

env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 30
  ANDROID_BUILD_TOOLS_VERSION: 30.0.0
  ANDROID_SDK_PACKAGES: system-images;android-30;google_apis_playstore;x86_64 platforms;android-30 build-tools;30.0.0 platform-tools emulator
  EMULATOR_TIMEOUT: 600
  EMULATOR_NAME: nexus


jobs:
  android-tests:
    timeout-minutes: 100
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Add avdmanager and sdkmanager to system PATH
        run: |
         echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH
      - name: Install Sdk
        run: |
          yes Y | sdkmanager --licenses
          sdkmanager --install ${ANDROID_SDK_PACKAGES}

      - name: Build emulator
        run: |
          echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
      - name: Launch emulator
        run: |
          chmod +x ./start_emu_headless.sh
          EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT EMULATOR_NAME=$EMULATOR_NAME ./start_emu_headless.sh
          screencapture screenshot.jpg
         # $ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png

     # - name: install recorder and record session
     #   run: |
          #    brew install ffmpeg
          #     $ANDROID_HOME/tools/emulator -port 4728 -verbose -no-window -no-audio -gpu swiftshader_indirect @nexus &
          #      ffmpeg -f avfoundation -i 0 -t 120 out.mov
         # node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 120 out.mov'); exec.exec('$ANDROID_HOME/tools/emulator -port 4728 -verbose -no-window -no-audio -gpu swiftshader_indirect @nexus &');"

      - name: Set up Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run local
        continue-on-error: true

        env:
         HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: upload video
       # uses: actions/upload-artifact@master
       # with:
        # name: out
       #  path: out.mov

        uses: actions/upload-artifact@v3
        with:
              name: screenshot.jpg
              path: screenshot.jpg




